# Dependencies
#markdown:         redcarpet
rouge:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            SapienzaNLP
subtitle:         Reading Group
tagline:          'Activity Blog of SapienzaNLP group at La Sapienza University of Rome'
description:      The group is focused on NLP and is specifically interested in Semantic Parsing, Word Sense Disambiguation and related topics.
  You can find out more about SepienzaNLP at <a href="http://lcl.uniroma1.it">sapienzanlp.uniroma1.it</a>></a>.
url: https://sapienzanlp.github.io
baseurl: /

author:
  name:           'Tommaso Pasini'
  url:            https://twitter.com/pasini_t

paginate:         5

# Custom vars
version:          2.1.0
